export const GET_SORTED_SUCCESS = "GET_SORTED_SUCCESS";
export const GET_APICHARACTERS_SUCCESS = "GET_APICHARACTERS_SUCCESS";
export const GET_APISPELLS_SUCCESS = "GET_APISPELLS_SUCCESS";

export const GET_DBCHARACTERS_SUCCESS = "GET_DBCHARACTERS_SUCCESS";
export const SAVE_CHARACTER_SUCCESS = "SAVE_CHARACTER_SUCCESS";
export const UPDATE_CHARACTER_SUCCESS = "UPDATE_CHARACTER_SUCCESS";
export const DELETE_CHARACTER_SUCCESS = "DELETE_CHARACTER_SUCCESS";

export const GET_DBSPELLS_SUCCESS = "GET_DBSPELLS_SUCCESS";
export const SAVE_SPELL_SUCCESS = "SAVE_SPELL_SUCCESS";
export const UPDATE_SPELL_SUCCESS = "UPDATE_SPELL_SUCCESS";
export const DELETE_SPELL_SUCCESS = "DELETE_SPELL_SUCCESS";

export const ASSIGN_HOUSE_SUCCESS = "ASSIGN_HOUSE_SUCCESS";
export const GET_HOUSE_SUCCESS = "GET_HOUSE_SUCCESS";