const GET_SORTED_SUCCESS = "GET_SORTED_SUCCESS";
const GET_APICHARACTERS_SUCCESS = "GET_APICHARACTERS_SUCCESS";
const GET_APISPELLS_SUCCESS = "GET_APISPELLS_SUCCESS";

const GET_DBCHARACTERS_SUCCESS = "GET_DBCHARACTERS_SUCCESS";
const SAVE_CHARACTER_SUCCESS = "SAVE_CHARACTER_SUCCESS";
const UPDATE_CHARACTER_SUCCESS = "UPDATE_CHARACTER_SUCCESS";
const DELETE_CHARACTER_SUCCESS = "DELETE_CHARACTER_SUCCESS";

const GET_DBSPELLS_SUCCESS = "GET_DBSPELLS_SUCCESS";
const SAVE_SPELL_SUCCESS = "SAVE_SPELL_SUCCESS";
const UPDATE_SPELL_SUCCESS = "UPDATE_SPELL_SUCCESS";
const DELETE_SPELL_SUCCESS = "DELETE_SPELL_SUCCESS";